version: 3

tasks:
  build:
    desc: Build
    aliases: [ make ]
    deps: [ generate-makefile ]
    cmds:
      - make

  generate-makefile:
    cmds:
      - cmake -S .
    sources:
      - CMakeLists.txt
    targets:
      - Makefile

  build-via-earthly:
    desc: Build via earthly
    cmds:
      - earthly --artifact +build/build build
