version: 3

tasks:
  build:
    desc: Build
    aliases: [ make ]
    deps: [ generate-makefile ]
    cmds:
      - make

  generate-makefile:
    cmds:
      - cmake -S .
    sources:
      - CMakeLists.txt
    targets:
      - Makefile

  build-via-earthly:
    desc: Build via earthly
    cmds:
      - earthly --artifact +build/build build

  build-docker:
    cmds:
      - earthly +build-docker

  run-docker:
    deps: [ build-docker ]
    cmds:
      - docker run --rm -it -p 6182:6182 ticktock:latest
